### ISSUE TITLE
Android passwords changed? Now different than Web and Desktop Java

### ISSUE THREAD

**Issue by e-geist** [Lyndir/MasterPassword#117] opened 2016-10-07 21:28 UTC
Hi,

I just got a new phone today and downloaded the Android version of MasterPassword from https://ssl.masterpasswordapp.com/ . 

I tried generating some passwords, but they are different than they used to be and different than the ones I get from the Web generator and the Desktop Java Android version.

The phone is a chinese LeEco LeMax2.

Did the algorithm change, is it a bug or did I do something wrong?

Thanks in advance.

**Comment by lhunath** [comment] 2016-10-30 13:57
Dupe of #127 ?

**Closed by lhunath** 2016-10-30 13:57 UTC
Labels: system-android

**Comment by diabolusss** [comment] 2017-07-06 14:34
Could someone, please, add to git or mail me latest MPW version of android app? I have the same issue, but could find only 2.1v application for android.
