### ISSUE TITLE
MasterPassword-Gui Copy issue on Linux

### ISSUE THREAD

**Issue by GreyAragami** [Lyndir/MasterPassword#150] opened 2017-01-04 14:03 UTC
Hello,

I'm using kernel 4.9 with stable manjaro and I've been stumbling on an issue lately. MasterPassword-gui is supposed to copy when you hit enter right? Well... in my case it doesn't it just closes the GUI. 

Is there something i'm missing? Or might this be an issue with MasterPassword's code? 

Kind regards,

**Comment by soamaven** [comment] 2017-01-05 23:09
Same issue. Seems to be a java thing becuase it has the same behavior on linux and windows.

**Comment by Binero** [comment] 2017-01-26 14:58
I an confirm this issue. There doesn't seem to be anything interesting in the logs. 

I tested it on a 64 bit Arch Linux installation using Java 7 and 8, both using OpenJDK.
```
15:39:23,539 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:39:23,539 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:39:23,539 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/usr/share/java/masterpassword-gui/masterpassword-gui.jar!/logback.xml]
15:39:23,560 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@375c56d3 - URL [jar:file:/usr/share/java/masterpassword-gui/masterpassword-gui.jar!/logback.xml] is not of type file
15:39:23,651 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:39:23,657 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:39:23,659 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:39:23,712 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
15:39:23,712 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
15:39:23,712 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
15:39:23,713 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.lyndir] to INFO
15:39:23,713 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:39:23,713 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:39:23,714 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:39:23,715 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@f48530a - Registering current configuration as safe fallback point

249                         GUI [INFO ] Local Revision:    <8f1d8976600b0305e8daade529ec8a073a4c7c57>
251                         GUI [INFO ] Upstream Revision: <8f1d8976600b0305e8daade529ec8a073a4c7c57>
```

**Comment by GreyAragami** [comment] 2017-01-26 21:50
Seems to work with masterpassword-gui 2.3-3 found in AUR.
Is the java version on the website up to date?

**Comment by Binero** [comment] 2017-01-27 15:13
I too am using the AUR package. I am running a GTK+ installation (GNOME), maybe that's related?

**Comment by lhunath** [comment] 2017-01-27 15:35
This sounds like some sort of an issue where Java isn't interacting well with X, whether it's caused by Java, X or an intermediary such as GNOME.  Regardless, I haven't the setup to reproduce and test this issue at the very moment.

**Comment by Binero** [comment] 2017-01-27 15:47
It's definitely not X. I don't even run X. I use Wayland, which is the default on GNOME.

**Comment by jan0sch** [comment] 2017-01-30 06:50
The problem lies in the behaviour of X regarding the clipboard and closing of applications. I already opened a pull request a while back: #139 

To put it short: The default behaviour erases the clipboard if the application from which it's content was copied is closed. The change in the pull request just disables the automatic closing to circumvent this.

**Comment by lhunath** [comment] 2017-02-05 15:53
Discussion continues in #139

**Closed by lhunath** 2017-02-05 15:53 UTC
Labels: system-java
