### ISSUE TITLE
software name

### ISSUE THREAD

**Issue by motherload** [Lyndir/MasterPassword#116] opened 2016-10-02 14:17 UTC
Just food for thought here. I know it's none of my business, but I suggest changing the name from "Master Password" to something more unique in order to promote a higher visibility. If you search for "master password" in reddit or google, you'll get a ton of results, almost none related to this software. I just came to know it from privacytools.io and I love it, and I wish it had a greater visibility.

Cheers!

**Comment by sahal2080** [comment] 2016-10-14 15:17
> If you search for "master password" in reddit or google, you'll get a ton of results, almost none related to this software

Aside from @motherload advice, which I second (and btw I apologize for somewhat hijacking your issue), the thing that kept me from actively using masterpassword was the risk of spoofing attacks. The scenario of such risk is simple:
- User, on their primary computing device, has downloaded and started using genuine masterpassword software with a _Master Password_ they created
- While not on their primary computing device/platform, user is creating an account for a new site and wish to use masterpassword. 
- User searches for masterpassword, finds a site that resembles their past experience of it and so proceed to download software appropriate for the platform
- User input their name,  _Master Password_ and then name of new site to the downloaded software to get a newly generated password
- Software was malicious. Damage, which might be huge, is done

Renaming here isn't a full blown solution but the generic nature of the current one only makes the spoofer's life easier. I have a couple of suggestions in mind but, due to a fair experience with neglected or dismissed comments on open-source projects, I'd rather hear from you first.

**Comment by lhunath** [comment] 2016-10-14 15:31
I concur.  A bit of extra related information:  A while ago I submitted a trade mark application to the EU Office for Harmonization in the Internal Market (OHIM) for the name "Master Password", specifically to aid in protecting the type of spoofing @sahal2080 highlighted.  The officer in charge of review rejected the application on the grounds of the name being too generic.

I am definitely open to looking for a more identifying mark.

**Comment by Mylainos** [comment] 2017-01-06 17:34
This application REALY need another name, so let's try to find a good one.
[Tessera](https://la.wikipedia.org/wiki/Tessera_(solutio)) mean password in Latin, so I propose **Tessera Password Manager**. See [wiktionary](https://en.wiktionary.org/wiki/tessera#Latin)

**Comment by lhunath** [comment] 2017-01-06 18:08
Although I realize the constraint this puts on eligible names, I would actually prefer if we could find a name that honours the current abbreviations `mpw` and `MP`.

**Comment by lhunath** [comment] 2017-01-06 18:10
In addition, it would be nice if the name, being its identity, could somehow convey the unique nature of mpw.  This isn't really a password "manager" as much as it's a static password generator.

**Comment by Mylainos** [comment] 2017-01-07 00:32
I agree with you on `password manager` but when I see `password generator` I think that I will generate a random password and I have to store it or remember it. Maybe `password generator/manager` is better because MPW "manage" your generated passwords.

Your last preference is the harder one. What about a name that abbreviates to mpw or MP followed by `, a password generator/manager`, but the name doesn't include password or something related. That way the name will be unique, sounds good, and everyone understand what this is about.

Or something that start with M and finish with Pass, like MasterPass (already taken by MasterCard). There are a lot of password manager that follow this pattern (LastPass, LesserPass...).

Too bad someone have already take the [Multipass](http://gbsoft.free.fr/) name, the reference to the 5th element is cool.

**Comment by lhunath** [comment] 2017-01-07 05:13
In a vague attempt at tackling the latter head-on, this is a list of all p-nouns that contain a w-noun per WordNet 3.0:  [pw.txt](https://github.com/Lyndir/MasterPassword/files/691268/pw.txt)

**Comment by Mylainos** [comment] 2017-01-09 00:44
**PROD**, Password Reproduced On Demand
**PROUD**, Password Reproduced On User Demand
**PARODy**, PAssword Reproduced On Demand (y?)
**SPHEROiD**, Static Password with High Entropy Reproduced On (i?) Demand

**Comment by Mylainos** [comment] 2017-01-09 01:12
**SPORADIC**, Secure (or Static) Password Offline Reproduced Anywhere and on Demand (i?) (c?)

**Comment by Mylainos** [comment] 2017-01-09 01:14
Try http://acronymcreator.net, it's very usefull.

**Comment by Mylainos** [comment] 2017-01-09 01:28
**SWORDPass**, Secure Well-knit Offline Reproduced on-Demand Password

**Comment by Mylainos** [comment] 2017-01-10 01:34
**SPORADIC**, Secure Password Obtained by Reproducing it Anywhere and on Demand which is Inaccessible even with Clues

**Comment by smichel17** [comment] 2017-01-10 01:45
RPW: Reproducible Password (manager). Not too memorable, but also not too different from `mpw`.

**Comment by fallerOfFalls** [comment] 2017-01-18 10:24
RePass, ReproPass, ReProPass - because you can reproduce it

FunctionalPass, or FuncPass, FunPass :P - because it's just a function that behaves the same way every time.

StateLessPass

ForgetPass - because it forgets your passwords.

I don't think any of these are 'the one' but hopefully inspiring?

MicroPass - because it's so small and simple.

**Comment by macuser666** [comment] 2017-04-01 16:35
Maybe one of these?
POSSESS : PasswOrd Secure StatelESS
PASSPORT:  PAssword Secure Stateless PORTable

**Comment by lhunath** [comment] 2017-04-01 16:52
With Master Password the first hits on Google now, I don't think this is that important anymore.  Also, I still like "Master Password" better than the other suggestions or anything else I can come up with.

**Comment by lhunath** [comment] 2017-04-06 04:02
Closing this issue for now while pending review of the CIPO.

[02469903.pdf](https://github.com/Lyndir/MasterPassword/files/901442/02469903.pdf)

**Closed by lhunath** 2017-04-06 04:02 UTC
Labels: category-suggestion, system-algorithm
